### ISSUE TITLE
Delete Tires Trash Date

### ISSUE THREAD

**Issue by jlaba** [condo4/carbudget#39]
If once clicked on trash date in the tire menu, it must be set. Once set, the tire could not be fitted again, even if the trash date is in the future.

Is there a way to clear the trash date field?

**Comment by condo4** [comment]
Hi,
I need to investigate, but today, I have no time to do this, perhaps in this summer...
In any case, you can open the database with a sqlite3 browser and change tire table...

**Comment by direc85** [comment]
Hi condo4,

I have used Car Budget for a few years now, and ran into this same problem. I'm not sure if I did the correct thing, but I forked your code base and fixed the issue described there. Please see https://github.com/direc85/carbudget for details. The issue itself is fixed in this commit: https://github.com/condo4/carbudget/commit/3be108fcbf66403cef4e063d716824f73e907b3c

I also touched the database loading mechanisms because of some corner cases I ran into, so I don't create pull request just yet. I am using this build and it seems to work just fine, but any rigorous testing hasn't been done.

Thanks!

**Comment by condo4** [comment]
Hi,
Thank you for your job ;-)
I very need to re-work on this application (I want to add a import/export function, and a Android portage)... I hope to have more time this winter...
For your fix, want you think it's working well, can you send me a Pull Request ?
I will try to rebuild an official package with the new Jolla SDK and perhaps a version for SailfishX...

**Comment by direc85** [comment]
Hi,
I was planning to implement backup and restore functionality, too (copying the db to/from Documents) and tweak the UI a bit more, but let's finish this first :)

I ran into some corner cases already and found some translation errors. I'll try to fix them soon. Ill send you a pull request after that.

I did my work using the latest SDK and my device is Sony Xperia X, so I can tell it works :)

**Comment by condo4** [comment]
Hi,
Very good job...
I merged all your work, and, I think, in a week (or two), I will generate a new release...
I wait 2 weeks, for new possible pull request for missing translations...
I don't have a Xperia, but I have a tablet, I will also try on this device...

**Comment by direc85** [comment]
Thanks!

I found a minor bug (annoying behavior) in my code, but I'm on a trip, so I can't fix it until next week. It doesn't change translations, I promise ;)

I have a Jolla 1, too, so I can test both devices. The tablet layout is challenging, but works for now.

Oh. I enabled some commented features in Statistics.qml, you might want to comment them out. They may not be release ready. Or I could start improving them...

**Comment by fferner** [comment]
Hey, great to see activity. I've also been using it for a few years now... 

Trying to update the German translation (unless someone else is working on that?) I came across (the recently introduce? strings) "trashed" and "untrash". I've got a few options so just wanted to clarify that the background is without diving into the code too much. Is trashed the state a set of tires ends up when they are deleted and untrash could be translated similar to undelete?

**Comment by direc85** [comment]
Yes, "trashed" means that the wheels are either (going to be) recycled or otherwise being permanently disposed of - not just being untrashed and kept in storage. Untrashing is the oppisite action.

Actually; I now think the correct term would be "dispose of" and its opposite could be... Uh... "salvage"? I gotta think about that, actually.

PS I'm thinking about preventing tire set deletion if it has mounting history. That messes up with history page.

**Comment by condo4** [comment]
Since, many translations and changed are planed, I think I will plan to build a new release only at the end of the month or later.
This leave more time to add new features, and to test the futur version.
I hope to have also more time to work on this application...
In all case, thanks for all your contributions !!!

**Comment by direc85** [comment]
This is now fixed in my latest pull request.

**Comment by direc85** [comment]
@condo4, isn't this fixed already? Could you close thia ticket, too?
