### ISSUE TITLE
Import 'Qt.labs.folderlistmodel 2.1' is not allowed

### ISSUE THREAD

**Issue by condo4** [condo4/carbudget#58]
QML files
=========
INFO [/usr/share/harbour-carbudget/qml/pages/TiremountView.qml] Uses Sailfish Silica Components (only reported once)
ERROR [/usr/share/harbour-carbudget/qml/pages/SelectImportFile.qml] Import 'Qt.labs.folderlistmodel 2.1' is not allowed
INFO [harbour-carbudget] Please see our FAQ here: https://harbour.jolla.com/faq#QML_API
FAILED

**Comment by dcaliste** [comment]
I had the same issue in dcaliste/maep-qt, I can make a PR to circumvent the harbour limitation if you want. This PR will add the Qt sources for FolderListModel and add it as a QML export from your own namespace so harbour won't complain. It's quite ugly and have to be updated each time Qt is updated.

Otherwise, you can switch to use Nemo.Filemanager or something, but it's more work…

What do you prefer?

**Comment by condo4** [comment]
This first way seem to be a good way for now...

Perhaps, if I will have more time in some month, I will look for 
Nemo.Filemanager integration, but, since we have a "ready" application, 
I think, the quicker way will be the best...

If you can do a PR, it's fine, else, I will try to find time to do it 
today...

Thanks,

Fabien


Le 30/05/2018 à 08:57, Damien Caliste a écrit :

**Comment by dcaliste** [comment]
Here it is (#59), I've tried quickly on my device and it seems to browse files properly (didn't try to actually import though, I don't have anything to import).
